# Generated by Django 2.1.5 on 2019-03-10 07:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import quiz.models.custom_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LTIUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(help_text='Used to store LTI consumer key', max_length=100)),
                ('userId', models.CharField(help_text='User ID as in the LTI Launch Request', max_length=200)),
                ('name', models.CharField(blank=True, help_text='Name of the user if available/given.', max_length=100, null=True)),
                ('email', models.CharField(blank=True, help_text='Email of the student if provided', max_length=100, null=True)),
                ('role', models.CharField(help_text='Role of the user', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthNonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(max_length=30)),
                ('nonce', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeServiceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lis_result_sourcedid', models.CharField(help_text='lis_result_sourcedid', max_length=200, null=True)),
                ('outcome_send_time', models.DateTimeField(null=True)),
                ('lis_outcome_service_url', models.TextField(help_text='lis_outcome_service_url ', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=100, null=True)),
                ('question_weight', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('serial_number', models.PositiveIntegerField(default=1, verbose_name='Serial Number')),
                ('draft_statement', models.TextField(default='', null=True)),
                ('draft_options_data', models.TextField(null=True)),
                ('draft_expected_response', models.TextField(null=True)),
                ('draft_other_data', models.TextField(null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('options_data', models.TextField(null=True)),
                ('expected_response', models.TextField(null=True)),
                ('other_data', models.TextField(null=True)),
                ('published', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(help_text='Used to store LTI consumer key', max_length=100)),
                ('resourceLinkId', models.CharField(help_text='Resource_link_id', max_length=100)),
                ('contextId', models.CharField(help_text='Context Id: Unique for each term (run) of the course', max_length=200)),
                ('createdOn', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('quizName', models.CharField(blank=True, max_length=100)),
                ('published', models.BooleanField(default=False)),
                ('isEverAttempted', models.BooleanField(default=False, help_text='Set to True if the Quiz has been attempted by at least one student')),
            ],
            options={
                'get_latest_by': 'createdOn',
            },
        ),
        migrations.CreateModel(
            name='QuizManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.LTIUser')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(null=True)),
                ('response', models.TextField(blank=True, default='{}')),
                ('start_time', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('end_time', models.DateTimeField(null=True)),
                ('submission_time', models.DateTimeField(null=True)),
                ('submitted', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': 'start_time',
            },
        ),
        migrations.CreateModel(
            name='QuizSettings',
            fields=[
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.Quiz')),
                ('deadline', models.DateTimeField(blank=True, help_text='Set the deadline for the Quiz. Leave blank if not required', null=True, verbose_name='Deadline')),
                ('duration', quiz.models.custom_fields.IntegerRangeField(blank=True, default=30, help_text='Set the duration of quiz in minutes. Leave blank if timer is not required', null=True, verbose_name='Duration')),
                ('timeBetweenAttempt', quiz.models.custom_fields.IntegerRangeField(default=0, help_text='Set the time between the two consecutive attempts.', null=True, verbose_name='Time Between Attempts')),
                ('maxAttempts', quiz.models.custom_fields.IntegerRangeField(blank=True, help_text='Set the maximum number of allowed attempts. Leave blank for unlimited attempts.', null=True, verbose_name='Maximum Attempts')),
                ('graded', models.BooleanField(default=False, help_text='Set whether the quiz is graded', verbose_name='Graded')),
                ('information', models.TextField(default='', help_text="Set the information that will be shown to the student on the quiz page.         This will be shown in a html modal on clicking the button 'Information'. Leave blank to hide the button.", verbose_name='Information')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.LTIUser'),
        ),
        migrations.AddField(
            model_name='quizmanager',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='outcomeservicedata',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='outcomeservicedata',
            name='response_sent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Response'),
        ),
        migrations.AddField(
            model_name='outcomeservicedata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.LTIUser'),
        ),
    ]
