# Generated by Django 2.1.5 on 2019-03-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsettings',
            name='graded',
            field=models.BooleanField(default=True, help_text='Set whether the quiz is graded', verbose_name='Graded'),
        ),
    ]
