# Generated by Django 2.1.5 on 2019-03-11 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190310_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('time_spent', models.PositiveIntegerField(blank=True, default=0, help_text='Store the time spent by the         on the `question` in this `response`')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Response')),
            ],
        ),
    ]
