# Generated by Django 2.1.5 on 2019-02-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190211_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='submission_time',
            field=models.DateTimeField(null=True),
        ),
    ]
