# Generated by Django 2.1.5 on 2019-02-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_response_submission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_timing',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='question',
            name='draft_statement',
            field=models.TextField(default='', null=True),
        ),
    ]
