# Generated by Django 2.1.5 on 2019-02-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20190213_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='draft_other_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='other_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='published',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
