# Generated by Django 2.1.5 on 2019-02-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20190214_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='group_number',
        ),
        migrations.RemoveField(
            model_name='response',
            name='response_timing',
        ),
    ]
