# Generated by Django 2.1.5 on 2019-02-20 20:35

from django.db import migrations, models
import quiz.models.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20190220_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsettings',
            name='information',
            field=models.TextField(default='', help_text="Set the information that will be shown to the student on the quiz page. This will be shown in a model on         clicking the button 'Information'. Leave blank to hide the button.", verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='quizsettings',
            name='maxAttempts',
            field=quiz.models.custom_fields.IntegerRangeField(blank=True, help_text='Set the maximum number of allowed attempts. Leave blank for unlimited attempts. ', null=True, verbose_name='Maximum Attempts'),
        ),
    ]
