# Generated by Django 2.1.5 on 2019-02-24 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20190220_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeServiceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lis_result_sourcedid', models.CharField(help_text='lis_result_sourcedid', max_length=200)),
                ('lis_outcome_service_url', models.TextField(help_text='lis_outcome_service_url ')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
        ),
        migrations.AlterField(
            model_name='ltiuser',
            name='userId',
            field=models.CharField(help_text='User ID as in the LTI Launch Request', max_length=200),
        ),
        migrations.AddField(
            model_name='outcomeservicedata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.LTIUser'),
        ),
    ]
