# Generated by Django 2.1.5 on 2019-02-25 21:54

from django.db import migrations, models
import django.db.models.deletion
import quiz.models.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20190224_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcomeservicedata',
            name='outcome_send_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='outcomeservicedata',
            name='response_sent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Response'),
        ),
        migrations.AlterField(
            model_name='outcomeservicedata',
            name='lis_outcome_service_url',
            field=models.TextField(help_text='lis_outcome_service_url ', null=True),
        ),
        migrations.AlterField(
            model_name='outcomeservicedata',
            name='lis_result_sourcedid',
            field=models.CharField(help_text='lis_result_sourcedid', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quizsettings',
            name='information',
            field=models.TextField(default='', help_text="Set the information that will be shown to the student on the quiz page.         This will be shown in a html modal on clicking the button 'Information'. Leave blank to hide the button.", verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='quizsettings',
            name='maxAttempts',
            field=quiz.models.custom_fields.IntegerRangeField(blank=True, help_text='Set the maximum number of allowed attempts. Leave blank for unlimited attempts.', null=True, verbose_name='Maximum Attempts'),
        ),
    ]
