# Generated by Django 2.1.5 on 2019-02-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20190225_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthNonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(max_length=30)),
                ('nonce', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
